name: build
on:
    push:
        branches:
            - master
    pull_request: ~
    schedule:
        - cron: 5 8 * * 3
jobs:
    checks:
        name: 'PHP ${{ matrix.php-versions }} with composer args: ${{ matrix.composer-args }}'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 3
            matrix:
                operating-system: [ubuntu-latest]
                php-versions:
                    - '7.3'
                    - '7.4'
                composer-args: ['--prefer-lowest --prefer-stable', '']
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: intl
                    coverage: none
            -   name: Install Composer dependencies
                run: composer update --no-progress --no-suggest --prefer-dist --no-interaction ${{ matrix.composer-args }}
            -   name: Validate composer
                run: composer validate --strict
            -   name: Check composer normalized
                run: composer normalize --dry-run
            -   name: Check style
                run: composer check-style
            -   name: Static analysis
                run: composer analyse
            -   name: Run phpunit
                run: composer phpunit
